### ISSUE TITLE
Can't find symbol this.webView.postInvalidateDelayed(delay);

### ISSUE THREAD

**Issue by AlexZhouAA** [woodyza/RedrawPlugin#2]
When I compiled my android apk, this plugin gave me an error:
../Redraw.java:28: error: can't find symbol  this.webView.postInvalidateDelayed(delay);
   symbol: method postInvalidateDelayed(long)
   location: variable webview of type CordovaWebView

I'm using cordova version 3.4.0-0.1.3

Could anyone help me out of this error.

Thanks

**Comment by woodyza** [comment]
Hmm I couldn't see a reason why this would happen, far as I could tell CordovaWebView still exposes the Android WebView, which still has that method on it. Can you build the apk successfully if you remove this plugin?

**Comment by woodyza** [comment]
Closing unless I get more feedback on this.

**Comment by pbrisson** [comment]
I'm getting the same issue with Android 4.4.1.

I can successfully build the APK if I remove the plugin.
