### ISSUE TITLE
Cannot find symbol this.postInvalidateDelayed(delay);

### ISSUE THREAD

**Issue by pbrisson** [woodyza/RedrawPlugin#5]
I know this is a dupe of #2 

I'm getting:

```
Redraw.java:28: error: cannot find symbol
this.postInvalidateDelayed(delay);
    ^
symbol: method postInvalidateDelayed(long)
```

I'm using Android 4.1.1. with CrossWalk. If if remove your plugin, I can successfully compile my app.

Let me know if you need any extra information!

Thanks for your time!

**Comment by woodyza** [comment]
Hey,

Never used Crosswalk before, but I'l have a scratch around and see if I can figure out what's happening.

The code in the line reported by that error isn't the same as in the source (this.postInvalidateDelayed instead of this.webView.postInvalidateDelayed), have you modified Redraw.java at all?

Are you using Cordova 4 and the CrossWalk Cordova WebView plugin in your project?

**Comment by woodyza** [comment]
After having a dig around it looks like the approach taken in this plugin is incompatible with Cordova 4, so if you're using that (or something like the CrossWalk-based Cordova Android based on 4+) it just won't work. 

The webview exposed by the framework is now an abstraction behind which the new pluggable webview model seems to have been built, upshot being it's not possible to access the underlying android webview in this manner any more to call postInvalidateDelayed.

It's a last resort using this plugin anyway, I would have hoped CrossWalk would have removed the need for this kind of skulduggery to trigger a webview redraw?

**Comment by pbrisson** [comment]
I was trying to use it for a very specific issue with CrossWalk + Google Maps Plugin, documented here: https://github.com/wf9a5m75/phonegap-googlemaps-plugin/issues/638

Thanks for your time! Since it's not supported, feel free to close this! ;)

**Comment by woodyza** [comment]
All good bud, sorry it couldn't help!
